version: "1.0.0"

services:
  mysql:
    image: localhost:5000/mysql:latest
    container_name: mysql-service
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
    ports:
      - 3307:3306
    volumes:
      - data:/var/lib/mysql

  spring:
    image: localhost:5000/amjedchakhis/backend:1.0.0
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - appnetwork

  angular:
    image: amjedchakhis/frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - spring
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge
volumes:
  data:
    driver: local
